apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: container-registry-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node202-container-registry-pv
  namespace: container-registry
spec:
  capacity:
    storage: 198Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: container-registry-local-storage
  local:
    path: /mnt/hdd1/container_registry/
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node202
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: node202-container-registry-pvc
   namespace: container-registry
   labels:
      app: docker-registry
spec:
  storageClassName: container-registry-local-storage
  volumeName: node202-container-registry-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 198Gi