apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node201-minio-pv
  namespace: minio
spec:
  capacity:
    storage: 198Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/hdd1/minio/
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node201
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: node201-minio-pvc
   namespace: minio
   labels:
      app: minio
spec:
  storageClassName: minio-local-storage
  volumeName: node201-minio-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 198Gi