apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
spec:
  image: minio/minio:RELEASE.2021-10-06T23-36-31Z
  imagePullPolicy: IfNotPresent
  credsSecret:
    name: minio-tenant-secret
  pools:
    - servers: 1
      volumesPerServer: 4  # At least 4 volumes required by minio in standalone mode(1 server mode).
      volumeClaimTemplate:
        metadata:
          name: minio-tenant-data
          namespace: minio
        spec:
          storageClassName: minio-local-storage
          volumeName: node201-minio-pv
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 37Gi  # 148 Gi divided by 4 volumes per server for 1 server.
  requestAutoCert: true