apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "app-sharing-key"
  name: "console"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.201
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9004
    targetPort: 9090
  - name: https
    port: 9005
    targetPort: 9443
  selector:
    {{- include "minio-operator.console-selectorLabels" . | nindent 4 }}
