apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio-operator.console-fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-operator.console-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-operator.console-selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: console-sa
    {{- with .Values.console.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.console.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: secret-volume
        secret:
          secretName: tls-ssl-minio
          items:
          - key: public.crt
            path: public.crt
          - key: private.key
            path: private.key
          - key: public.crt
            path: CAs/public.crt
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: secret-volume
            mountPath: /root/.minio/certs  # This should be /<user-running-minio>/.minio/certs
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
          - containerPort: 9090
            name: http
          - containerPort: 9443
            name: https
          args:
          - server
          env:
          - name: CONSOLE_OPERATOR_MODE
            value: "on"
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
      {{- with .Values.console.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end}}
