apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "app-sharing-key"
  name: "operator"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.86.201
  externalTrafficPolicy: Cluster
  ports:
    - port: 9003
      name: https
      targetPort: 4222
  selector:
    operator: leader
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
