apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  # Comment the line below if you do not want to assign a specific IP address.
  loadBalancerIP: 192.168.86.200
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443