apiVersion: v1
kind: Namespace
metadata:
  name: test-load-balancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-load-balancer
  labels:
    app: test-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: testlb-nginx
  template:
    metadata:
      labels:
        pod-label: testlb-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: testlb-nginx
  namespace: test-load-balancer
  labels:
    app: test-lb
spec:
  selector:
    pod-label: testlb-nginx
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: true
  name: testlb-ingress
  namespace: test-load-balancer
spec:
  rules:
  - http:
      paths:
      - path: /testlb(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: testlb-nginx
            port:
              number: 80
